### PR TITLE
First version of slides for week 4

### PR DESCRIPTION
**Pull request by pmarjora**
This isn't complete, but I'd like to test that I understand how the pull request works.

### CODE REVIEW

**Comment by EmilHvitfeldt** [comment]
Everything looks great so far. You can continue to push to this PR and tell me once you are ready to have it moved in

**Comment by EmilHvitfeldt** [comment]
https://github.com/USCbiostats/PM566/blob/51bbf76a14701ffc32e5663a8d81531eaf18737c/static/slides/04-visualization/IntroToGGplot.Rmd#L356

Background images are defined within xaringan and will not transfer easily to .HTML files as "background" have a different meaning there.

**Comment by pmarjora** [comment]
yeah, that's fine. I was just exploring Xaringen really. I think, ultimately, I'm going to go with Rmd, exporting to html, because I was having too much trouble sizing things on the slides. 
Ideally, we should probably all do the same thing, to make it easier on whoever ends up presenting the course. But it doesn't have to be Rmd/html.

**Comment by pmarjora** [comment]
I've now completed the full first draft of the slides for Week 4, so please incorporate it at this point.

**Pull request merged**
